// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using WebApi_IMDb_Clone.Entities;

namespace WebApi_IMDb_Clone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi_IMDb_Clone.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = "01/01/1941",
                            FullName = "Full Name 1"
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = "01/01/1941",
                            FullName = "Full Name 2"
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = "01/01/1941",
                            FullName = "Full Name 3"
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = "01/01/1941",
                            FullName = "Full Name 4"
                        });
                });

            modelBuilder.Entity("WebApi_IMDb_Clone.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Category1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Category2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Category3"
                        });
                });

            modelBuilder.Entity("WebApi_IMDb_Clone.Entities.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Descrip descrip",
                            DirectorFullName = "Director Name",
                            MovieName = "Movie Name 1",
                            ReleaseDate = "01/01/2021"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descrip descrip",
                            DirectorFullName = "Director Name",
                            MovieName = "Movie Name 2",
                            ReleaseDate = "01/01/2021"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descrip descrip",
                            DirectorFullName = "Director Name",
                            MovieName = "Movie Name 3",
                            ReleaseDate = "01/01/2021"
                        });
                });

            modelBuilder.Entity("WebApi_IMDb_Clone.Entities.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductionName = "A Company"
                        },
                        new
                        {
                            Id = 2,
                            ProductionName = "B Company"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
